name: Test

on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
    steps:
      - uses: actions/checkout@v2
      - run: .\PsBuilder.init.ps1
